### ISSUE TITLE
Auto messaging heads up

### ISSUE THREAD

**Issue by nrmitchi** [crockpotveggies/tinderbox#10]
Some of the functionality went against my expectations, so this is more a heads up for anyone else.

I ran this and logged in hoping to just look at the interface and such, but didn't really plan to 'turn it on' (I was expecting a 'Start' button or something). Needless to say, it immediately started messaging everyone that I had matched with 'manually'.

Perhaps a toggle for the automated features should be added, or a warning on the login page, and it's not a big deal, but for now I just thought I'd give anyone seeing this a heads up before you decide to try to go secretly exploring.

**Comment by Telemakhos** [comment]
+1

**Comment by crockpotveggies** [comment]
I've added a note in the second line in the README. This is actually a very good suggestion.
