### ISSUE TITLE
Age preferences are not being saved.

### ISSUE THREAD

**Issue by dastan101** [crockpotveggies/tinderbox#11]
When I change the age range of a one side and press save the results are not updated and it goes back to the default age range.

But, when I take both sides and move it as a group and press save, it works.

**Comment by crockpotveggies** [comment]
Hmm, not seen this issue before. It's possible that Tinder itself may not be properly saving the data on its end (perhaps a sync issue somewhere in their API). Also possible that the Knockout.js custom binding for the slider isn't working properly. Will be a while until I could have a quick fix. In the meantime, you could easily log into the app via your phone and update the settings there.

**Comment by crockpotveggies** [comment]
@dastan101 is this still happening after you try from the mobile app? Does it sync properly?
