### ISSUE TITLE
No new recommendations are found

### ISSUE THREAD

**Issue by xdmx** [crockpotveggies/tinderbox#13]
This are the steps I do:
- start the server
- update the discovery age/distance
- go to matchmaker
- see the new profiles
- see that are managed by the bot
- after few minutes go back to the matchmaker
- no new profiles show up
- if I update the age/distance (using exactly the same as before) new profiles show up

Until I manually update the discovery setting the /recommendations returns "null"

I don't know if this is some kind of protection tinder put in place after seeing your work

**Comment by crockpotveggies** [comment]
Sounds like a case-by-case issue. I used to have this all the time if I exhausted all new recommendations for a given location. Updating your discovery preferences tends to "force" Tinder to provide new recs.

**Comment by xdmx** [comment]
That's weird considering that I haven't signed in on Tinder for few months and living in a city with more than 2 millions of people I'd expect more than 20-30 new profiles (which are returned after I update the preferences). I gets the same problem also when I set the age to the min and max, including for sure many profiles I never saw, still they don't show up after the first /recomendations request

**Comment by crockpotveggies** [comment]
Have you tried deleting and recreating your account? It could be a bug with their matchmaking system, or possibly you were shadow-banned for whatever reason.

**Comment by xdmx** [comment]
Checking on the app I can see new profiles, I've also tried to delete the account on tinder and create a new one and delete all tinderbox's data, but I get the same null response after I match the first batch of ~30 profiles

**Comment by geometry9** [comment]
I believe this is a bug in the new matchmaker system. I get the same problem, especially when moving between my locations that are more than 5 miles apart.  It says I have no new matches, until I change the distance range. (This is in the android app mind you)

**Comment by crockpotveggies** [comment]
Going to close this since it looks to be on the Tinder-side.
