### ISSUE TITLE
Typo in FunMessages.scala

### ISSUE THREAD

**Issue by scubadiver124** [crockpotveggies/tinderbox#14]
Line 34: "...I've been looking fo ways..."

**Comment by fsargent** [comment]
It adds character. 
If I were you I'd customize the messages. The defaults are really creepy.

**Comment by scubadiver124** [comment]
Yea I was slightly surprised when all of my previous matches were sent messages saying I couldn't wait to introduce them to my mom. I was even more surprised when one actually responded favourably...

**Comment by crockpotveggies** [comment]
I removed a couple messages which some may think are creepy. I had a very vanilla/fun profile so often people took them as humor. However, I removed them with a commit today since it could hurt others who are trying out the bot. Also, I merged your PR.
