### ISSUE TITLE
Match controls (Like, Dislike, Undo) are missing (JavaScript errors)

### ISSUE THREAD

**Issue by joschi** [crockpotveggies/tinderbox#17]
The controls for potential matches (Like, Dislike, Undo) on the "Bot Logs" and "Dashboard" pages are missing.

The web console of Chrome (Version 40.0.2214.111 (64-bit), Mac OS X 10.10) displays an error in knockout.min.js, line 63:

> Uncaught TypeError: Unable to process binding "visible: function (){return task().contains('message') }"
Message: undefined is not a function

![tinderbox JS error](https://cloud.githubusercontent.com/assets/43951/6144555/2a8be99e-b1d9-11e4-81b2-adf54f5b31b7.png)
![tinderbox JS error](https://cloud.githubusercontent.com/assets/43951/6144559/2fb18906-b1d9-11e4-9f73-62d1b4012460.png)

**Comment by crockpotveggies** [comment]
Some sort of issue with the Knockout.js bindings at first glance. Can you paste a full stack trace?

**Comment by joschi** [comment]
How exactly could I create a stack trace of that JavaScript function call in Chrome?

**Comment by damianpoole** [comment]
Change contains to be indexOf in app/views/Bot/bot.scala.html
```
<i class="fa fa-envelope" data-bind="visible: task().indexOf('message') !== -1"></i>
````

**Comment by joschi** [comment]
Confirmed. The changes from @damianpoole in `app/views/Bot/bot.scala.html` and `app/views/Application/dashboard.scala.html` fixed the issue.
