### ISSUE TITLE
Compile Failure

### ISSUE THREAD

**Issue by SXRWahrheit** [crockpotveggies/tinderbox#28]
[error] C:\temp\tinderbox-master\app\services\SparkService.scala:4: object mllib
 is not a member of package org.apache.spark
[error] import org.apache.spark.mllib.classification.NaiveBayes
[error]                         ^
[error] C:\temp\tinderbox-master\app\services\SparkService.scala:5: object mllib
 is not a member of package org.apache.spark
[error] import org.apache.spark.mllib.linalg.Vectors
[error]                         ^
[error] C:\temp\tinderbox-master\app\services\SparkService.scala:6: object mllib
 is not a member of package org.apache.spark
[error] import org.apache.spark.mllib.regression.LabeledPoint
[error]                         ^
[error] C:\temp\tinderbox-master\app\services\SparkService.scala:40: not found:
value LabeledPoint
[error]       LabeledPoint(parts(0).toDouble, Vectors.dense(parts(1).split(' ').
map(_.toDouble)))
[error]       ^
[error] C:\temp\tinderbox-master\app\services\SparkService.scala:47: not found:
value NaiveBayes
[error]     val model = NaiveBayes.train(training, lambda = 1.0)
[error]                 ^
[error] 5 errors found
[error] (compile:compile) Compilation failed
[error] Total time: 14 s, completed Feb 14, 2015 8:19:24 AM

**Comment by crockpotveggies** [comment]
I assume you just pulled the latest changes?

```
sbt clean
sbt compile
sbt run
```

Also, take a look here if you have further issues booting up the app: https://github.com/crockpotveggies/tinderbox/issues/23

**Comment by SXRWahrheit** [comment]
I pulled the latest changes and did clean before compiling. That's the error I got.

**Comment by SXRWahrheit** [comment]
Good to know about the data folder, giving that a go now. Would recommend putting this in big bold letters somewhere prominent. :)

**Comment by crockpotveggies** [comment]
For whatever reason your GIT isn't removing files that were removed with the last commit. If you're worried about losing your models, you could try copying the data folder to a safe place and re-download the repo. If that doesn't work then the commit is missing data (unlikely). Let me know if that works.
