### ISSUE TITLE
warn 

### ISSUE THREAD

**Issue by AppoPro** [crockpotveggies/tinderbox#31]
[info] Compiling 74 Scala sources and 8 Java sources to /var/www/tinderbox-master/target/scala-2.10/classes...
[warn] /var/www/tinderbox-master/app/utils/tinder/TinderApi.scala:79: play.api.libs.json.JsValue and None.type are unrelated: they will most likely never compare equal
[warn]                 if(res==None || res==null) throw new Exception("Data was not wrapped in a results class. Could not parse.")
[warn]                       ^
[warn] /var/www/tinderbox-master/app/utils/tinder/TinderWS.scala:57: class PerRequestConfig in package client is deprecated: see corresponding Javadoc for more information.
[warn]         val config = new PerRequestConfig()
[warn]             ^
[warn] /var/www/tinderbox-master/app/utils/tinder/TinderWS.scala:57: class PerRequestConfig in package client is deprecated: see corresponding Javadoc for more information.
[warn]         val config = new PerRequestConfig()
[warn]                          ^
[warn] there were 19 feature warning(s); re-run with -feature for details
[warn] four warnings found

**Comment by crockpotveggies** [comment]
These are okay, unless someone wants to redesign the client used to connect to the Tinder API.
