### ISSUE TITLE
Number of bot tasks displayed incorrectly

### ISSUE THREAD

**Issue by wnstnsmth** [crockpotveggies/tinderbox#36]
On the dashboard, the number of bot tasks always shows the same number. In my case, it climbed up to 318 and then stayed there. In the shell, I only have 130 or so bot tasks remaining. I tried logging out and reloading the app, even deleting the browser's cache didn't help.

**Comment by crockpotveggies** [comment]
Going to close this since it's actually accurate. The tasks in the shell represent analysis and other background tasks. The ones in the dashboard represent logging and moves made using the API. I'll change the name of the metric in the dashboard in a commit later today.

**Comment by wnstnsmth** [comment]
I think there was a misunderstanding on my side, too. I thought it would show the *remaining* tasks, and not the *completed*.

**Comment by crockpotveggies** [comment]
It's all good, I can see how it could be misinterpreted. I think changing it to "Tinder Actions" is a lot more reflective of what it actually is.
