### ISSUE TITLE
MessageTree with multiple heights

### ISSUE THREAD

**Issue by AnthonyTuil** [crockpotveggies/tinderbox#37]
Hi,

I try to figure out how to make a multiple height MessageTree.
The code work well, the line "Creating new message intro task for match XXXXXXXX" is display but when I go to "inbox" the messages didn't appear. 
 Here is my code in FunMessages.scala : 

package models.bot.tasks.message

package models.bot.tasks.message

/**
 * A list of fun, pre-defined message trees.
 */
object FunMessages {

  def messages = List(
    MessageTree(
      value = "1",
      right = Some(MessageTree(
          value = "2",
          right = Some(MessageTree(
            value = "3",
            right = None,
            left = None
          )),
          left = Some(MessageTree(
            value = "4",
            right = None,
            left = None
          ))
          )),
      left = Some(MessageTree(
        value = "5",
        right = Some(MessageTree(
          value = "6",
          right = None,
          left = None
          )),
        left = Some(MessageTree(
          value = "7",
          right = None,
          left = None
          ))
      ))
    ),

  )

}

Thank you

**Comment by crockpotveggies** [comment]
Looks valid, so it could be a different problem. Do your matches already have empty conversations? And can you look for a note in the Terminal/shell log that looks like this?
```[info] application - [tinderbot] Tasks queue size is currently 35```

What is the task queue size? If it is greater than 10, you'll probably have to wait for the facial models to finish calculating before messaging begins.

**Comment by AnthonyTuil** [comment]
The task queue size is 49, so yes I probably have to wait. 
Thank you for your responses

**Comment by AnthonyTuil** [comment]
It didn't update the messages. Do I have to clean or do something else to have the new messages sent ?

**Comment by crockpotveggies** [comment]
If you've modified the code, it will require a re-build. Check out the instructions here on how to do so: https://github.com/crockpotveggies/tinderbox/wiki/Editing-the-Code. That means shutting down the app.

If you're going to do some heavy developing, you could potentially run the app with incremental compiling by running the command `sbt ~run`. That will create an SBT shell which will re-build the code as you edit it. The prerequisites in the link above will also help you set that up.
