### ISSUE TITLE
Disable facial recognition

### ISSUE THREAD

**Issue by DrewDe** [crockpotveggies/tinderbox#38]
Hi, first of all thank you for this code, it’s very smart.
I’m quite a beginner at scala and I would like to know if there is some line of code that I can edit or comment in order to disable all the « facial recognition » part. In order to have just the messageTree send to people and like everybody ? 
Thank you for you response.

DrewD

**Comment by crockpotveggies** [comment]
Thanks for messaging. The code really isn't set up to be broken into functionality like this, and I personally couldn't support it myself. It kind of defeats the whole point of the project.

However, you're more than welcome to fork it and get some technical help. I just don't have the capacity to do so myself.

Cheers
