### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by jovehl** [crockpotveggies/tinderbox#5]
Fun stuff!
Can't seem to get my access token tho. 
I get the error: 
SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Center for more information.

any clue why that is?

**Comment by jovehl** [comment]
Got it to work by being really quick with copying the url before the warning popped up.

**Comment by kylepierce** [comment]
Had the same issue. Copy and pasting work. Thanks jovehl
