### ISSUE TITLE
I use Tinder Passport - will Bot set up matches across the world?

### ISSUE THREAD

**Issue by robthegentleman** [crockpotveggies/tinderbox#50]
Tinder recently introduced Tinder Plus, a subscription-based platform with two premium features:

1) Undo (re-do last swipe in the case of a mistake)
2) Passport (geolocate anywhere in the world and be able to swipe and be swiped in that location)

I finally have the Bot up and running and it is going nuts on my 538 matches (many of whom I've never messaged). Will it start setting up dates across the world? I'm already getting tons of replies. Oops.

R.

**Comment by robthegentleman** [comment]
When I use Passport, I end up swiping in Scandanavian countries most of the time (these women are phenomenal). I should add that most of these girls can speak and understand English, but not well all the time. I wonder what updates/additions to the code can be brainstormed.

**Comment by crockpotveggies** [comment]
Hi Rob not sure if I can really help here. The bot is tied directly to your account so anything on your account is subject to the bot. I'm not quite sure what your question is so going to close this issue for now. Thanks.

**Comment by robthegentleman** [comment]
Thanks @crockpotveggies - quick question: any updates/changes that are done to the code... how do I implement them? Do I copy/paste it into the terminal? I appreciate your time.

**Comment by crockpotveggies** [comment]
For best results you can start with a simple code editor like Sublime http://www.sublimetext.com/ and then you will need to "build and compile" the code. There's a script for that which you can run from Terminal. See this wiki page: https://github.com/crockpotveggies/tinderbox/wiki/Editing-the-Code

If you're having further trouble, not sure if I can help more. It might be best to get help from a coding buddy who knows some Java/Scala.

Best,

Justin
