### ISSUE TITLE
how can I swipe everyone right?

### ISSUE THREAD

**Issue by markyann11** [crockpotveggies/tinderbox#51]
I don't want the app to swime anyone left, how can I make it swipe everyone right?

**Comment by crockpotveggies** [comment]
Hi some people have asked for help with this and I'll be clear that I have no intention of supporting that functionality since it is outside the scope of the project. If you Google tinderbot you will find projects meant exactly for this. Thanks

**Comment by sebastianbarfort** [comment]
I respect that, of course, and I'm not looking for that functionality, but I've been wondering: isn't that the most efficient way to approach your project as well? Swipe everyone right and then do facial recognition on the ones the user is matched with? Seems very inefficient to have the app calculate and classify a lot of candidates you'll never be matched with anyway? Thanks for a really cool project.

**Comment by crockpotveggies** [comment]
Interesting thought, but it actually wouldn't. There are a few important reasons:

1. You'll actually be grouped with other users differently with a swipe-all strategy (there appears to be user grouping in the background by Tinder)
2. Tinder is starting to limit total daily swipes
3. You'll significantly increase the number of conversation tasks in the bot queue, increasing the total processing power for the bot

**Comment by sebastianbarfort** [comment]
Interesting, I hadn't thought about user grouping on the Tinder side. On the other hand, if it's static matching then a swipe all strategy would still be optimal methinks. 2 and 3 are definitely good arguments though.
