### ISSUE TITLE
Difficult to get FB token because of redirect

### ISSUE THREAD

**Issue by javajosh** [crockpotveggies/tinderbox#53]
FB itself seems to be running a script that obscures the token that running loadFBLogin() attempts to create. It would seem that the problem is some sort of redirecting script that eliminates the URL itself, showing only this:

**Comment by crockpotveggies** [comment]
No way to change this and you'll have to live with it or create your own browser that can block the behavior. Its for security reasons by Facebook. Sorry. Going to close this.

**Comment by javajosh** [comment]
A related question - what is the fb id? I managed to grab the token, but I'm not sure what ID you're asking for, and it's not in the readme. (I haven't written an FB client yet, but looking forward to trying it someday)

**Comment by crockpotveggies** [comment]
Looks like 1001200481082 or a similar number. You can use this http://findmyfacebookid.com/ to look it up or sometimes if you refresh the page and re-paste the token Tinderbox will auto-populate it for you (doesn't consistently work for unknown reasons).
