### ISSUE TITLE
Mean Column calculated and not used

### ISSUE THREAD

**Issue by JoakimP1** [crockpotveggies/tinderbox#55]
Looks like this is calculated and not used in that function scope.
https://github.com/crockpotveggies/tinderbox/blob/master/app/utils/face/MatrixHelpers.scala#L89

**Comment by crockpotveggies** [comment]
Nice spot, I think you're right there. Can you perform a test compile without it and submit a PR?

**Comment by JoakimP1** [comment]
Cheers. I removed it and compiled using sbt ~run, without any issues I could see.
I must admit that Scala/Java is not my normal weapon of choice, but it all seemed straight forward.

**Comment by crockpotveggies** [comment]
Appreciate it. Yea SBT is great for the simple things though in larger projects can get a little tricky. I merged the PR!
