### ISSUE TITLE
Rollover profil photo doesn't work

### ISSUE THREAD

**Issue by 2803media** [crockpotveggies/tinderbox#57]
Is it normal that the rollover the profil photo in the TinderBot page doesn't open the popup with the photo?

**Comment by crockpotveggies** [comment]
Yea it is, I didn't add it since it actually rolls over the icon itself and I didn't customize the plugin enough to modify the position. Are you open to submitting a PR that addresses the issue? I didn't think it was important enough.

**Comment by 2803media** [comment]
thanks for your reply I will investigate this point, if I found a solution i will submit a PR

**Comment by crockpotveggies** [comment]
Great thank you!
