### ISSUE TITLE
Upon first run, asked all girls "Do you like avocados?" Please kill me.

### ISSUE THREAD

**Issue by davidcox143** [crockpotveggies/tinderbox#59]
Not sure if anyone has had much success with this opening line... consider changing it?

**Comment by crockpotveggies** [comment]
Hi David there are instructions on the README that link you to the file you need to change if you want to include your own openers. Please read through the README and wiki before booting up! It will be helpful if you want to change the messaging around.

Going to close this for now. Thanks.

**Comment by davidcox143** [comment]
Doh, my bad. Read just enough of the readme to get it running and then got overly excited. I'll be heading to the store now to purchase 100 jars of guacamole.

**Comment by robthegentleman** [comment]
@crockpotveggies is there a follow-up message for this opening line? My bot is running every day but still hasn't sent any follow-up after the girls answer.

**Comment by crockpotveggies** [comment]
Yesterday I pulled in a downstream bug fix where sometimes the message tree wasn't correctly identified due to {name} templating. Can you update your local copy and let me know if it fixed the issue?

**Comment by robthegentleman** [comment]
@crockpotveggies I deleted Tinderbox from my computer entirely and downloaded it again from here. Is this how you mean to update my local copy? There still hasn't been any follow-up messages sent, but I noticed the tasks queue size has gone up substantially... which I assume is a good thing.

**Comment by crockpotveggies** [comment]
You can actually do a `git fetch` which will preserve your data. It will re-process all of your models, but yes that queue size is probably a good thing. You can also check the DEBUG statements for `MessageReplyTask` creation which will happen when it first boots up.

**Comment by robthegentleman** [comment]
@crockpotveggies the task queue size has hit 0, and now the bot keeps repeating the following:



[error] application - An error occurred retrieving full history for 90dfe1d5-aac4-4e59-889b-b9bf83f13693.
[error] application - Reason: No session found for user with api_token: 90dfe1d5-aac4-4e59-889b-b9bf83f13693
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [tinderbot] created new Facial Check task for token 90dfe1d5-aac4-4e59-889b-b9bf83f13693
[debug] application - [tinderbot] New task received for supervision
[debug] application - [tinderbot] created new Recommendation task for token 90dfe1d5-aac4-4e59-889b-b9bf83f13693
[debug] application - [tinderbot] created new Message Analysis task for token 90dfe1d5-aac4-4e59-889b-b9bf83f13693
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] Starting new facial check task.
[warn] application - [tinderbot] No manual yes/no data available, recommendations may be inaccurate.
[info] application - [tinderbot] Received command: run
[debug] application - [tinderbot] New task received for supervision
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] Starting new recommendations task.
[warn] application - [tinderbot] Waiting to start automatic Swipes. User needs to make more choices to ensure accuracy.
[info] application - [tinderbot] Received command: run
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] New task received for supervision
[debug] application - [tinderbot] Starting new message analysis task.
com.fasterxml.jackson.databind.JsonMappingException: Invalid JSON. Needed [matches, blocks, deleted_lists, last_activity_date, lists], but found [status, error].
java.lang.Exception: Data was not wrapped in a results class. Could not parse.
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:109)
	at utils.tinder.TinderApi$$anonfun$tinderPost$1.apply(TinderApi.scala:99)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[error] application - An error occurred retrieving full history for 90dfe1d5-aac4-4e59-889b-b9bf83f13693.
[error] application - Reason: No session found for user with api_token: 90dfe1d5-aac4-4e59-889b-b9bf83f13693
[debug] application - [tinderbot] Message history was empty.
[info] application - [tinderbot] Received command: run




I shut it down and re-opened, and its still doing the same thing. Also, I am getting this when doing a git fetch:


Robs-iMac:~ CharlesRyan$ git fetch
fatal: Not a git repository (or any of the parent directories): .git

**Comment by crockpotveggies** [comment]
That's a common error, can't remember if I put it on the wiki but `No session found for user with api_token: 90dfe1d5-aac4-4e59-889b-b9bf83f13693` means that your API token with Tinder has expired. You'll have to logout, restart the app, and log back in. I'll update the wiki if it's not on there already. It will appear here: https://github.com/crockpotveggies/tinderbox/wiki/Common-Errors.

Also, please do a `git fetch` since I've also updated the dist JAR which may address your reply issue.

**Comment by robthegentleman** [comment]
@crockpotveggies slightly embarrassing, and tried my best to figure out myself, but how do you do a git fetch?

**Comment by crockpotveggies** [comment]
@robthegentleman can't really do a lesson here but I can refer you to some help/tutorial pages like this one: https://www.atlassian.com/git/tutorials/.

This might help: https://www.atlassian.com/git/tutorials/syncing/git-fetch

**Comment by robthegentleman** [comment]
@crockpotveggies I think I figured it out. Can you confirm? I've illustrated what I did below. It fetched 8 updates. I've rebooted the program and things seem to be running more smoothly now (task size has gone up too). 

Last login: Mon Mar 23 13:23:37 on ttys002
Robs-iMac:~ CharlesRyan$ git remote add tinderbox http://github.com/crockpotveggies/tinderbox
...
Robs-iMac:~ CharlesRyan$ git fetch tinderbox

**Comment by crockpotveggies** [comment]
Yep that should bring you up to date. If it stops replying please update me since it means there's another bug.

**Comment by robthegentleman** [comment]
@crockpotveggies update: it has stayed stuck on/repeating the same tasks queue size number for the last 20 mins. No new replies sent. I will try rebooting my computer

**Comment by robthegentleman** [comment]
@crockpotveggies it's gotten worse now. I had everything working (besides the replies to the avocado opener) before the git fetch, and I was using Java 7u80. None of the other updates from Java out there (7u75, 7u76, 8u40, etc.) worked. Since doing the git fetch, I've ran the bot on all of the Java versions mentioned and it ends up crashing within 2-3 mins of starting up.

**Comment by crockpotveggies** [comment]
Sorry not sure I can be of much help here since I don't have access to your machine. My only other suggestion is try starting from scratch (it's possible you were accidentally using an old "data" folder). There's a common errors page on the wiki which may help. Too many possibilities.

**Comment by robthegentleman** [comment]
@crockpotveggies hey man. Finally got it working. It has sent all the matches the follow-up avocado lines. However, it's sending the same line(s) multiple times to the same matches (between 2-5 times). The girls are annoyed haha. What should I do? Seriously though, thanks for your help to-date.

**Comment by crockpotveggies** [comment]
Yikes! ha sorry that all your matches were annoyed. Well for the annoyed girls I'd just tell them it's a glitch in Tinder and you know nothing about it ;)

As for the repeating messages, it sounds like the stop gaps aren't being properly applied. I might have a chance to look at that later this week, unless someone can step in beforehand.

**Comment by robthegentleman** [comment]
@crockpotveggies sounds good haha thanks man. No worries, I handled the disgruntled women. Some of them were so dramatic haha good riddance. If you want me to put it up as an open issue on here, let me know.

**Comment by crockpotveggies** [comment]
Yes please open a separate issue :)
