### ISSUE TITLE
TypeError: data.notifications is null

### ISSUE THREAD

**Issue by iamrekcah** [crockpotveggies/tinderbox#63]
This error shows up in the JavaScript console repeatedly (probably because of `setInterval()`). 

It's probably enough to put a if-not-null check around [the if statement](https://github.com/crockpotveggies/tinderbox/blob/abbd694d06fa1123dc92a18c02a44feb4f2a8faa/app/views/main.scala.html#L169).

**Comment by crockpotveggies** [comment]
Merged.
