### ISSUE TITLE
Inbox "Heads Up" warning alerts twice

### ISSUE THREAD

**Issue by iamrekcah** [crockpotveggies/tinderbox#69]
##### Affected Tinderbox version
This has been tested on the latest version of Tinderbox, but I've seen it since the beginning. 

##### Affected Browsers
I've also tested it on Firefox (on Linux) and Chrome 41 (on Windows). 

##### Issue
Although, that shouldn't matter because I found the [incriminating line of code](https://github.com/crockpotveggies/tinderbox/blob/d0ac176569e2828b3e3951bb1833a4b9d34345d6/app/views/main.scala.html#L191). The code is using a JQuery selector to grab **all** `<div class="wrapper wrapper-content">` elements. Turns out, there's more than one in *Inbox*. I'll be submitting a pull request soon, I just want to document the issue first, and test the patch a bit more.

![2015-04-06 22_55_09-inbox](https://cloud.githubusercontent.com/assets/1663284/7016780/54c73044-dcb1-11e4-8121-bef5bb324934.png)

**Comment by crockpotveggies** [comment]
Awesome. Feel free to submit the PR and I can merge it.
