### ISSUE TITLE
javac not found

### ISSUE THREAD

**Issue by thoroc** [crockpotveggies/tinderbox#8]
```
[error] (compile:compile) java.io.IOException: Cannot run program "javac": CreateProcess error=2, The system cannot find the file specified
```

However "javac" is on the system as I can call it from the cmd line .... So what am I doint wrong?

**Comment by dastan101** [comment]
Seems like your path is not picked up correctly. Try "which javac" and see if the paths are correct. I also suggest to update.

**Comment by thoroc** [comment]
ouch ```which``` under windows .... anyway, I ran the cmd under cygwin:
```
/cygdrive/c/Program Files/Java/jdk1.7.0_75/bin/javac
```
Despite the fact that I have just installed JDK8 .... I don't like windows.

**Comment by Bioto** [comment]
On another issue @crockpotveggies said its built on java 7 so that might have something to do with it.

**Comment by thoroc** [comment]
Well I was keeping java 7 to run minecraft for some mods. But I installed the latest jdk8, and had to point to version 8 in the registry (for what ever reason) and now it is working?!

Well at least it did compile. 

Maybe it was due to the fact that I have the JAVA path quoted to ensure no breakage with the space in the windows file system?
