### ISSUE TITLE
No main class detected

### ISSUE THREAD

**Issue by phazer33** [crockpotveggies/tinderbox#9]
Have latest java SDK installed. Ran sbt clean and compile. When I do sbt run this is the output:

[warn] No main class detected
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 0 s, completed Feb 10, 2015 11:31:08 AM

**Comment by Bioto** [comment]
Did compile have any errors?

**Comment by phazer33** [comment]
C:\Users\NickPC\Desktop\tinderbox-master>sbt compile

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
port was removed in 8.0
[info] Set current project to tinderbox-master (in build file:/C:/Users/NickPC/D
esktop/tinderbox-master/)
[info] Updating {file:/C:/Users/NickPC/Desktop/tinderbox-master/}tinderbox-maste
r...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
  [info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
  [info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
  [info] Resolving org.scala-lang#jline;2.10.4 ...
  [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 1 s, completed Feb 10, 2015 11:34:00 AM

**Comment by phazer33** [comment]
this isnt Mac OS only correct?

**Comment by crockpotveggies** [comment]
Is it possibly an older version of SBT? If I recall the version used with Tinderbox is 0.13.2.

**Comment by mariorodriguespt** [comment]
I've have the same issue at mac os yosemite with version: `sbt launcher version 0.13.7`

**Comment by phazer33** [comment]
same issues using sbt 0.13.2

**Comment by crockpotveggies** [comment]
By chance do you have any other SBT plugins installed? Also, are you using the OSX .app launcher to boot it up?

**Comment by crockpotveggies** [comment]
@phazer33 sorry just saw your OSX-only comment. Right now the bot works best in a UNIX environment. I've heard of a lot of issues in Windows (it has to do with some bugs in configs in SBT I think). I've heard some some booting it up in Cygwin to work around the issues.

**Comment by crockpotveggies** [comment]
Added a new commit to eliminate SBT. Hopefully this simplifies how things are running in the JVM and problems with classes not being loaded into the classpath. Going to close this issue (and a few others related to it).
